# - name: Install required dependencies
#   yum:
#     name:
#       - java-21-openjdk
#       - fontconfig
#     state: present

# - name: Disable Setup wizard
#   lineinfile:
#     path: /etc/environment
#     line: 'JAVA_OPTS="-Djenkins.install.runSetupWizard=false"'
#     create: yes
#   become: yes

# - name: Add Jenkins repo
#   get_url:
#     url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
#     dest: /etc/yum.repos.d/jenkins.repo

# - name: Import Jenkins GPG key
#   rpm_key:
#     key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
#     state: present

# - name: Upgrade all packages
#   yum:
#     name: '*'
#     state: latest

# - name: Install Jenkins
#   yum:
#     name: jenkins
#     state: present

# - name: Ensure Jenkins Groovy init directory exists
#   file:
#     path: /var/lib/jenkins/init.groovy.d
#     state: directory
#     owner: jenkins
#     group: jenkins
#     mode: '0755'

# - name: Deploy Jenkins Groovy security script from template
#   template:
#     src: security.groovy.j2
#     dest: /var/lib/jenkins/init.groovy.d/security.groovy
#     owner: jenkins
#     group: jenkins
#     mode: '0644'

# - name: Ensure Jenkins init.groovy.d directory exists
#   file:
#     path: /var/jenkins_home/init.groovy.d
#     state: directory
#     owner: jenkins
#     group: jenkins
#     mode: '0755'

# - name: Disable Jenkins setup wizard
#   copy:
#     src: roles/jenkins/scripts/disable-setup-wizard.groovy
#     dest: /var/jenkins_home/init.groovy.d/disable-setup-wizard.groovy
#     owner: jenkins
#     group: jenkins
#     mode: '0644'

# - name: Reload systemd daemon
#   command: systemctl daemon-reload

# - name: Ensure Jenkins is enabled and started
#   systemd:
#     name: jenkins
#     enabled: yes
#     state: started

# - name: Open port 8080 in firewalld
#   firewalld:
#     port: 8080/tcp
#     permanent: yes
#     state: enabled
#     immediate: yes
#   when: ansible_distribution == "OracleLinux"

# - name: Include plugin installer
#   include_tasks: install_plugins.yml
#   vars:
#     role_path: "{{ role_path }}"

- name: Ensure jenkins_home exists with correct perms
  file:
    path: /srv/jenkins
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"
  become: true

- set_fact:
    jenkins_home: /srv/jenkins

- name: Ensure init.groovy.d exists
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    mode: "0755"
  become: true

- name: Deploy admin user script (from Vaulted vars)
  template:
    src: security.groovy.j2
    dest: "{{ jenkins_home }}/init.groovy.d/10-create-admin.groovy"
    mode: "0644"
  become: true
  
- name: Copy plugins.txt to host
  copy:
    src: roles/jenkins/files/plugins.txt
    dest: /tmp/plugins.txt
    mode: "0644"

# - name: Run Jenkins container (wizard off, plugins, init script mounted)
#   community.docker.docker_container:
#     name: jenkins
#     image: jenkins/jenkins:latest
#     restart_policy: unless-stopped
#     published_ports:
#       - "8080:8080"
#     volumes:
#       - /tmp/plugins.txt:/usr/share/jenkins/ref/plugins.txt
#       - "{{ jenkins_home }}:/var/jenkins_home"
#     env:
#       JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
#     docker_host: unix:///var/run/docker.sock
#   become: true

- name: Recreate Jenkins container with SELinux labels and RO plugins.txt
  become: true
  community.docker.docker_container:
    name: jenkins
    image: jenkins/jenkins:latest
    state: started
    recreate: true
    restart_policy: unless-stopped
    published_ports:
      - "8080:8080"
    volumes:
      - /srv/jenkins:/var/jenkins_home:Z
      - /tmp/plugins.txt:/usr/share/jenkins/ref/plugins.txt:ro,Z
    env:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    docker_host: unix:///var/run/docker.sock