- name: Install dnf-plugins-core
  dnf:
    name: dnf-plugins-core
    state: present

- name: Add Docker CE repo
  command: >
    dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker packages
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user | default('opc') }}"
    groups: docker
    append: yes

- name: Install pip
  package:
    name: python3-pip
    state: present

- name: Install Docker SDK for Python
  pip:
    name: docker
    executable: pip3

- name: Log in to Docker registry (optional for private registries)
  docker_login:
    registry_url: "{{ docker_registry_url | default('') }}"
    username: "{{ docker_registry_user | default(omit) }}"
    password: "{{ docker_registry_password | default(omit) }}"
  when: docker_registry_user is defined