- name: Configure Docker
  hosts: docker
  become: yes
  roles:
    - docker

- name: Configure Jenkins server
  hosts: jenkins
  become: yes
  roles:
    - jenkins

- name: Configure Web nodes
  hosts: web
  become: yes
  roles:
    - web
